### PR TITLE
[curator-viewer] enabled toast instead of alert for copy paste, and fixed streaming toast

### PR DESCRIPTION
**Pull request by CharlieJCJ**
Addressed #153 
**Changes**: 
- Reduced the TOAST_REMOVE_DELAY from 1000000ms to 3000ms for quicker dismissal of toast notifications.
- Enabled updates toast in DatasetViewer page
- Enabled toast updates in DetailsSidebar view
- Added <Toaster /> component to the root layout to enable toast notifications.

**Testings**:
- tested on all litellm examples, openai examples. 
- on both streaming and non streaming. 

Quick demo: 
[video](https://github.com/user-attachments/assets/649b4c29-ddfc-4fda-b19e-9c09c4865ca1)

**Note: This PR only affects UI, doesn't affect the copy paste behaviors in colab embedded view. The issue with colab embedded view is an common issue with <iframe> for security reasons.**

### CODE REVIEW

**Comment by CharlieJCJ** [comment]
Need additional testing on colab after a built UI.

**Comment by madiator** [comment]
Is this still a draft PR?
Also, the video is a bit unclear: are you clicking "Copy" several times or a single click is triggering those many toasts?

**Comment by CharlieJCJ** [comment]
Added a note in the PR description: **Note: This PR only affects UI, doesn't affect the copy paste behaviors in colab embedded view. The issue with colab embedded view is an common issue with <iframe> for security reasons**

**Comment by vutrung96** [comment]
sorry missed this PR. LGTM

**Review by vutrung96 — APPROVED** [review]

**Pull request merged**
