### PR TITLE
[curator-viewer] add time logging and curator viewer show distribution

### PR DESCRIPTION
**Pull request by CharlieJCJ**
**Changes**:
- added generation time logging
- add generation time UI, in distribution view, sortable table view and detail view
- added requests & responses overlay time series plot (default view)
- enabled all with streaming
- Resolves 
  - #145 
  - partially address #105 for better bins, but addressing outliers, still need work. Perhaps selecting a range for user to zoom in if they see most of the points lie in a small region?
  - #150

New GenericResponse:
```python
class GenericResponse(BaseModel):
    response_message: Optional[Dict[str, Any]] | str = None
    response_errors: Optional[List[str]] = None
    raw_response: Optional[Dict[str, Any]]
    raw_request: Optional[Dict[str, Any]] = None
    generic_request: GenericRequest
    created_at: datetime.datetime
    finished_at: datetime.datetime
```

https://github.com/user-attachments/assets/a8751cb1-4bf4-4921-b17d-b3fd8726803c

https://github.com/user-attachments/assets/57877738-0d83-49ca-98c7-3ecb8c5a3e7a

Nice to have: 
- https://www.infoworld.com/article/2334935/recharts-intro-to-javascript-charting.html (brush component in UI), for selecting time range

### CODE REVIEW

**Comment by CharlieJCJ** [comment]
Ready for review @vutrung96 @RyanMarten

**Comment by CharlieJCJ** [comment]
point1, 2 resolved.
point 3 addressed. 
point 4 is due to not `poetry shell` during testing.

**Review by vutrung96 — APPROVED** [review]
can confirm it works on my end and the graph looks beautiful. thank you @CharlieJCJ !

**Review by vutrung96 — CHANGES_REQUESTED** [review]
Screenshot 2024-11-19 at 10 29 45 PM
actually one more issue, seems like text is off here (both lines say responses received)

**Review by vutrung96 — APPROVED** [review]

**Pull request merged**
