### PR TITLE
Add a starter example for running UI for the first time

### PR DESCRIPTION
**Pull request by CharlieJCJ**
Address #31 

https://github.com/user-attachments/assets/5616d1a2-5dba-4b67-9d7b-84be4a8fa462

### CODE REVIEW

**Comment by CharlieJCJ** [comment]
Let me know if there's a more appropriate starter example to place here. I'll just open the PR here, and we can swap the example easily @madiator.

**Comment by madiator** [comment]
This is fine. Once we update README.md, we can update this as well?

**Comment by madiator** [comment]
Can we resolve this PR?

**Comment by CharlieJCJ** [comment]
Is the action item to substitute the example using #43?

**Review by madiator — APPROVED** [review]

**Comment by CharlieJCJ** [comment]
I'll update the example in a future PR

**Pull request merged**
